name: rolla_demo_app
description: Rolla Demo Flutter App Task
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.1
  get_it: ^9.1.0
  dartz: ^0.10.1
  equatable: ^2.0.7
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  fl_chart: ^1.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  flutter_svg: ^2.2.3
  shimmer: ^3.0.0
  flutter_inset_shadow: ^2.0.3
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.10.4
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  mockito: ^5.6.1
  intl_utils: ^2.8.12
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/icons/app_icon.png"
  image_path_ios: "assets/icons/app_icon.png"
  remove_alpha_ios: false

flutter_native_splash:
  color: "#ffffff"            # background color for splash
  color_dark: "#000000"
  image: "assets/icons/app_icon.png"
  android: true
  ios: true
  web: false

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/data/scores.json
    - assets/icons/
    - assets/images/

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Regular.ttf
        - asset: assets/fonts/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Outfit-Bold.ttf
          weight: 700

