name: rolla_demo_app
description: Rolla Demo Flutter App Task
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.2
  get_it: ^8.2.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  fl_chart: ^0.60.0
  google_fonts: ^5.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  intl_utils: ^2.9.0
  cupertino_icons: ^1.0.5
  http: ^0.14.0
  flutter_svg: ^2.2.3
  pdf: ^3.9.0
  printing: ^5.14.0
  permission_handler: ^10.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  freezed: ^2.2.0
  json_serializable: ^6.5.0
  mockito: ^5.4.0
  intl_utils: ^2.9.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/scores.json
    - assets/icons/
    - assets/images/

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Regular.ttf
        - asset: assets/fonts/Outfit-Bold.ttf
          weight: 700
